version: '3'

services:
  backend:
    build: ./backend/
    image: flask-demo
    container_name: backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend/
    image: react-demo
    container_name: frontend
    ports:
      - "3000:3000"